@baseUrl = http://localhost:3000

### Criar
# @name createEquipe
GET {{baseUrl}}/equipe/importar
Content-Type: application/json

### Listar
# @name createEquipe
GET {{baseUrl}}/equipe
Content-Type: application/json