@baseUrl = http://localhost:3000

### Criar
# @name createJogador
GET {{baseUrl}}/jogador/importar
Content-Type: application/json

### Listar
# @name createJogador
GET {{baseUrl}}/jogador
Content-Type: application/json