@baseUrl = http://localhost:3000

### Criar
# @name createScout
POST {{baseUrl}}/scout/seed
Content-Type: application/json

### Listar
# @name createScout
GET {{baseUrl}}/scout
Content-Type: application/json